### ISSUE TITLE
Error when run in debian 10

### ISSUE THREAD

**Issue by csphoniex** [neo7530/conax-ca#1]
root@localhost:~/conax# ./conax-ecmg.x86_64 7002
keys.txt opened

ECM-Key #20:
BB AA 99 88 77 66 55 44 FF EE DD CC 33 22 11 00

ECM-Key #21:
77 66 55 44 BB AA 99 88 33 22 11 00 FF EE DD CC

*** Error in `./conax-ecmg.x86_64': double free or corruption (!prev): 0x0000561                                                                                                                                                             0974f1010 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7fdad0aedbfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7fdad0af3fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7fdad0af480e]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x132)[0x7fdad0ae3c42]
./conax-ecmg.x86_64(+0x2010)[0x561097028010]
./conax-ecmg.x86_64(+0x2be4)[0x561097028be4]
./conax-ecmg.x86_64(+0x103d)[0x56109702703d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fdad0a9d2e1]
./conax-ecmg.x86_64(+0xeba)[0x561097026eba]
======= Memory map: ========
561097026000-56109702b000 r-xp 00000000 07:11 3022334                    /root/c                                                                                                                                                             onax/conax-ecmg.x86_64
56109722a000-56109722b000 r--p 00004000 07:11 3022334                    /root/c                                                                                                                                                             onax/conax-ecmg.x86_64
56109722b000-56109722c000 rw-p 00005000 07:11 3022334                    /root/c                                                                                                                                                             onax/conax-ecmg.x86_64
5610974f1000-561097512000 rw-p 00000000 00:00 0                          [heap]
7fdacc000000-7fdacc021000 rw-p 00000000 00:00 0
7fdacc021000-7fdad0000000 ---p 00000000 00:00 0
7fdad0866000-7fdad087c000 r-xp 00000000 07:11 1704101                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libgcc_s.so.1
7fdad087c000-7fdad0a7b000 ---p 00016000 07:11 1704101                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libgcc_s.so.1
7fdad0a7b000-7fdad0a7c000 r--p 00015000 07:11 1704101                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libgcc_s.so.1
7fdad0a7c000-7fdad0a7d000 rw-p 00016000 07:11 1704101                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libgcc_s.so.1
7fdad0a7d000-7fdad0c12000 r-xp 00000000 07:11 1704609                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libc-2.24.so
7fdad0c12000-7fdad0e12000 ---p 00195000 07:11 1704609                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libc-2.24.so
7fdad0e12000-7fdad0e16000 r--p 00195000 07:11 1704609                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libc-2.24.so
7fdad0e16000-7fdad0e18000 rw-p 00199000 07:11 1704609                    /lib/x8                                                                                                                                                             6_64-linux-gnu/libc-2.24.so
7fdad0e18000-7fdad0e1c000 rw-p 00000000 00:00 0
7fdad0e1c000-7fdad0e3f000 r-xp 00000000 07:11 1704605                    /lib/x8                                                                                                                                                             6_64-linux-gnu/ld-2.24.so
7fdad1035000-7fdad1037000 rw-p 00000000 00:00 0
7fdad103e000-7fdad103f000 rw-p 00000000 00:00 0
7fdad103f000-7fdad1040000 r--p 00023000 07:11 1704605                    /lib/x8                                                                                                                                                             6_64-linux-gnu/ld-2.24.so
7fdad1040000-7fdad1041000 rw-p 00024000 07:11 1704605                    /lib/x8                                                                                                                                                             6_64-linux-gnu/ld-2.24.so
7fdad1041000-7fdad1042000 rw-p 00000000 00:00 0
7ffd57d73000-7ffd57d94000 rw-p 00000000 00:00 0                          [stack]
7ffd57d9f000-7ffd57da2000 r--p 00000000 00:00 0                          [vvar]
7ffd57da2000-7ffd57da3000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsysca                                                                                                                                                             ll]
Aborted

**Comment by thejackal2017** [comment]
i had the same problem , I don't know if i fixed it correctly ,but this is what i did : 

the keys.txt file by default contains the following keys : 
bb aa 99 88 77 66 55 44 ff ee dd cc 33 22 11 00

77 66 55 44 bb aa 99 88 33 22 11 00 ff ee dd cc

when changing the first key to the following : 
bb aa 99 88 77 66 55 44 ff ee dd cc 33 22 11 0**5**

and tried again it worked . 

Regards

**Comment by neo7530** [comment]
maybe some sort of buffer over-/underflow. I added the source, so you can check for yourself.
